// <auto-generated />
using System;
using DiagramManager.Infrastructure.Data;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Migrations;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;
using Npgsql.EntityFrameworkCore.PostgreSQL.Metadata;

#nullable disable

namespace DiagramManager.Infrastructure.Data.Migrations
{
    [DbContext(typeof(WorkspaceDbContext))]
    [Migration("20260717081232_AddDiagramTypeToDiagramVersion")]
    partial class AddDiagramTypeToDiagramVersion
    {
        /// <inheritdoc />
        protected override void BuildTargetModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasAnnotation("ProductVersion", "9.0.0")
                .HasAnnotation("Relational:MaxIdentifierLength", 63);

            NpgsqlModelBuilderExtensions.UseIdentityByDefaultColumns(modelBuilder);

            modelBuilder.Entity("DiagramManager.Domain.Entities.Diagram", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uuid");

                    b.Property<DateTime>("CreatedAt")
                        .HasColumnType("timestamp with time zone");

                    b.Property<string>("Description")
                        .IsRequired()
                        .HasColumnType("text");

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasColumnType("text");

                    b.Property<Guid>("WorkspaceId")
                        .HasColumnType("uuid");

                    b.HasKey("Id");

                    b.HasIndex("WorkspaceId");

                    b.ToTable("DIAGRAMS", (string)null);
                });

            modelBuilder.Entity("DiagramManager.Domain.Entities.DiagramShare", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uuid");

                    b.Property<Guid>("DiagramId")
                        .HasColumnType("uuid");

                    b.Property<string>("PermissionLevel")
                        .IsRequired()
                        .HasColumnType("text");

                    b.Property<Guid>("SharedWithUserId")
                        .HasColumnType("uuid");

                    b.HasKey("Id");

                    b.HasIndex("DiagramId");

                    b.ToTable("DIAGRAM_SHARES", (string)null);
                });

            modelBuilder.Entity("DiagramManager.Domain.Entities.DiagramVersion", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uuid");

                    b.Property<string>("AiReview")
                        .HasColumnType("text");

                    b.Property<float?>("AiScore")
                        .HasColumnType("real");

                    b.Property<Guid>("DiagramId")
                        .HasColumnType("uuid");

                    b.Property<string>("DiagramType")
                        .HasColumnType("text");

                    b.Property<string>("RawFormat")
                        .IsRequired()
                        .HasColumnType("text");

                    b.Property<string>("Status")
                        .IsRequired()
                        .HasColumnType("text");

                    b.Property<string>("StorageUrl")
                        .IsRequired()
                        .HasColumnType("text");

                    b.Property<DateTime>("UploadedAt")
                        .HasColumnType("timestamp with time zone");

                    b.Property<int>("VersionNumber")
                        .HasColumnType("integer");

                    b.HasKey("Id");

                    b.HasIndex("DiagramId");

                    b.ToTable("DIAGRAM_VERSIONS", (string)null);
                });

            modelBuilder.Entity("DiagramManager.Domain.Entities.Workspace", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uuid");

                    b.Property<DateTime>("CreatedAt")
                        .HasColumnType("timestamp with time zone");

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasColumnType("text");

                    b.Property<Guid>("UserId")
                        .HasColumnType("uuid");

                    b.HasKey("Id");

                    b.ToTable("WORKSPACES", (string)null);
                });

            modelBuilder.Entity("DiagramManager.Domain.Entities.Diagram", b =>
                {
                    b.HasOne("DiagramManager.Domain.Entities.Workspace", "Workspace")
                        .WithMany("Diagrams")
                        .HasForeignKey("WorkspaceId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Workspace");
                });

            modelBuilder.Entity("DiagramManager.Domain.Entities.DiagramShare", b =>
                {
                    b.HasOne("DiagramManager.Domain.Entities.Diagram", "Diagram")
                        .WithMany("Shares")
                        .HasForeignKey("DiagramId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Diagram");
                });

            modelBuilder.Entity("DiagramManager.Domain.Entities.DiagramVersion", b =>
                {
                    b.HasOne("DiagramManager.Domain.Entities.Diagram", "Diagram")
                        .WithMany("Versions")
                        .HasForeignKey("DiagramId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Diagram");
                });

            modelBuilder.Entity("DiagramManager.Domain.Entities.Diagram", b =>
                {
                    b.Navigation("Shares");

                    b.Navigation("Versions");
                });

            modelBuilder.Entity("DiagramManager.Domain.Entities.Workspace", b =>
                {
                    b.Navigation("Diagrams");
                });
#pragma warning restore 612, 618
        }
    }
}
