// <auto-generated />
using System;
using AIArchitectureReviewer.Infrastructure.Data;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Migrations;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;
using Npgsql.EntityFrameworkCore.PostgreSQL.Metadata;

#nullable disable

namespace AIArchitectureReviewer.Infrastructure.Migrations
{
    [DbContext(typeof(ApplicationDbContext))]
    [Migration("20260706072745_InitialCreate")]
    partial class InitialCreate
    {
        /// <inheritdoc />
        protected override void BuildTargetModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasAnnotation("ProductVersion", "9.0.0")
                .HasAnnotation("Relational:MaxIdentifierLength", 63);

            NpgsqlModelBuilderExtensions.UseIdentityByDefaultColumns(modelBuilder);

            modelBuilder.Entity("AIArchitectureReviewer.Domain.Entities.AiPrompt", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uuid");

                    b.Property<string>("DiagramType")
                        .IsRequired()
                        .HasColumnType("text");

                    b.Property<bool>("IsActive")
                        .HasColumnType("boolean");

                    b.Property<string>("PromptText")
                        .IsRequired()
                        .HasColumnType("text");

                    b.Property<int>("Version")
                        .HasColumnType("integer");

                    b.HasKey("Id");

                    b.ToTable("AI_PROMPTS", (string)null);
                });

            modelBuilder.Entity("AIArchitectureReviewer.Domain.Entities.AnalysisReport", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uuid");

                    b.Property<Guid>("AiPromptId")
                        .HasColumnType("uuid");

                    b.Property<DateTime>("CreatedAt")
                        .HasColumnType("timestamp with time zone");

                    b.Property<Guid>("DiagramVersionId")
                        .HasColumnType("uuid");

                    b.Property<string>("MarkdownReport")
                        .IsRequired()
                        .HasColumnType("text");

                    b.Property<string>("RawAiResponse")
                        .IsRequired()
                        .HasColumnType("text");

                    b.Property<float>("TotalScore")
                        .HasColumnType("real");

                    b.HasKey("Id");

                    b.HasIndex("AiPromptId");

                    b.ToTable("ANALYSIS_REPORTS", (string)null);
                });

            modelBuilder.Entity("AIArchitectureReviewer.Domain.Entities.Feedback", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uuid");

                    b.Property<string>("Comment")
                        .IsRequired()
                        .HasColumnType("text");

                    b.Property<DateTime>("CreatedAt")
                        .HasColumnType("timestamp with time zone");

                    b.Property<int>("Rating")
                        .HasColumnType("integer");

                    b.Property<Guid>("ReportId")
                        .HasColumnType("uuid");

                    b.Property<Guid>("UserId")
                        .HasColumnType("uuid");

                    b.HasKey("Id");

                    b.HasIndex("ReportId");

                    b.ToTable("FEEDBACKS", (string)null);
                });

            modelBuilder.Entity("AIArchitectureReviewer.Domain.Entities.ReportDetail", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uuid");

                    b.Property<string>("Description")
                        .IsRequired()
                        .HasColumnType("text");

                    b.Property<string>("ElementId")
                        .IsRequired()
                        .HasColumnType("text");

                    b.Property<string>("IssueType")
                        .IsRequired()
                        .HasColumnType("text");

                    b.Property<Guid>("ReportId")
                        .HasColumnType("uuid");

                    b.HasKey("Id");

                    b.HasIndex("ReportId");

                    b.ToTable("REPORT_DETAILS", (string)null);
                });

            modelBuilder.Entity("AIArchitectureReviewer.Domain.Entities.SystemRule", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uuid");

                    b.Property<string>("DiagramType")
                        .IsRequired()
                        .HasColumnType("text");

                    b.Property<bool>("IsActive")
                        .HasColumnType("boolean");

                    b.Property<string>("RegexOrCondition")
                        .IsRequired()
                        .HasColumnType("text");

                    b.Property<string>("RuleName")
                        .IsRequired()
                        .HasColumnType("text");

                    b.HasKey("Id");

                    b.ToTable("SYSTEM_RULES", (string)null);
                });

            modelBuilder.Entity("AIArchitectureReviewer.Domain.Entities.AnalysisReport", b =>
                {
                    b.HasOne("AIArchitectureReviewer.Domain.Entities.AiPrompt", "AiPrompt")
                        .WithMany("AnalysisReports")
                        .HasForeignKey("AiPromptId")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired();

                    b.Navigation("AiPrompt");
                });

            modelBuilder.Entity("AIArchitectureReviewer.Domain.Entities.Feedback", b =>
                {
                    b.HasOne("AIArchitectureReviewer.Domain.Entities.AnalysisReport", "Report")
                        .WithMany("Feedbacks")
                        .HasForeignKey("ReportId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Report");
                });

            modelBuilder.Entity("AIArchitectureReviewer.Domain.Entities.ReportDetail", b =>
                {
                    b.HasOne("AIArchitectureReviewer.Domain.Entities.AnalysisReport", "Report")
                        .WithMany("ReportDetails")
                        .HasForeignKey("ReportId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Report");
                });

            modelBuilder.Entity("AIArchitectureReviewer.Domain.Entities.AiPrompt", b =>
                {
                    b.Navigation("AnalysisReports");
                });

            modelBuilder.Entity("AIArchitectureReviewer.Domain.Entities.AnalysisReport", b =>
                {
                    b.Navigation("Feedbacks");

                    b.Navigation("ReportDetails");
                });
#pragma warning restore 612, 618
        }
    }
}
