// <auto-generated />
using System;
using AIArchitectureReviewer.Infrastructure.Data;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Migrations;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;
using Npgsql.EntityFrameworkCore.PostgreSQL.Metadata;
using Pgvector;

#nullable disable

namespace AIArchitectureReviewer.Infrastructure.Migrations
{
    [DbContext(typeof(ApplicationDbContext))]
    [Migration("20260715121255_RemovePromptTextAndVersion")]
    partial class RemovePromptTextAndVersion
    {
        /// <inheritdoc />
        protected override void BuildTargetModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasAnnotation("ProductVersion", "9.0.0")
                .HasAnnotation("Relational:MaxIdentifierLength", 63);

            NpgsqlModelBuilderExtensions.HasPostgresExtension(modelBuilder, "vector");
            NpgsqlModelBuilderExtensions.UseIdentityByDefaultColumns(modelBuilder);

            modelBuilder.Entity("AIArchitectureReviewer.Domain.Entities.AiPrompt", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uuid");

                    b.Property<string>("DiagramType")
                        .IsRequired()
                        .HasColumnType("text");

                    b.Property<bool>("IsActive")
                        .HasColumnType("boolean");

                    b.HasKey("Id");

                    b.ToTable("AI_PROMPTS", (string)null);
                });

            modelBuilder.Entity("AIArchitectureReviewer.Domain.Entities.AnalysisReport", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uuid");

                    b.Property<Guid>("AiPromptId")
                        .HasColumnType("uuid");

                    b.Property<DateTime>("CreatedAt")
                        .HasColumnType("timestamp with time zone");

                    b.Property<Guid>("DiagramVersionId")
                        .HasColumnType("uuid");

                    b.Property<string>("MarkdownReport")
                        .IsRequired()
                        .HasColumnType("text");

                    b.Property<string>("RawAiResponse")
                        .IsRequired()
                        .HasColumnType("text");

                    b.Property<float>("TotalScore")
                        .HasColumnType("real");

                    b.HasKey("Id");

                    b.HasIndex("AiPromptId");

                    b.ToTable("ANALYSIS_REPORTS", (string)null);
                });

            modelBuilder.Entity("AIArchitectureReviewer.Domain.Entities.ChatMessage", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uuid");

                    b.Property<Guid>("ChatSessionId")
                        .HasColumnType("uuid");

                    b.Property<string>("Content")
                        .IsRequired()
                        .HasColumnType("text");

                    b.Property<DateTime>("CreatedAt")
                        .HasColumnType("timestamp with time zone");

                    b.Property<string>("Role")
                        .IsRequired()
                        .HasColumnType("text");

                    b.HasKey("Id");

                    b.HasIndex("ChatSessionId");

                    b.ToTable("CHAT_MESSAGES", (string)null);
                });

            modelBuilder.Entity("AIArchitectureReviewer.Domain.Entities.ChatSession", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uuid");

                    b.Property<DateTime>("CreatedAt")
                        .HasColumnType("timestamp with time zone");

                    b.HasKey("Id");

                    b.ToTable("CHAT_SESSIONS", (string)null);
                });

            modelBuilder.Entity("AIArchitectureReviewer.Domain.Entities.Feedback", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uuid");

                    b.Property<string>("Comment")
                        .IsRequired()
                        .HasColumnType("text");

                    b.Property<DateTime>("CreatedAt")
                        .HasColumnType("timestamp with time zone");

                    b.Property<int>("Rating")
                        .HasColumnType("integer");

                    b.Property<Guid>("ReportId")
                        .HasColumnType("uuid");

                    b.Property<Guid>("UserId")
                        .HasColumnType("uuid");

                    b.HasKey("Id");

                    b.HasIndex("ReportId");

                    b.ToTable("FEEDBACKS", (string)null);
                });

            modelBuilder.Entity("AIArchitectureReviewer.Domain.Entities.ReportDetail", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uuid");

                    b.Property<string>("Description")
                        .IsRequired()
                        .HasColumnType("text");

                    b.Property<string>("ElementId")
                        .IsRequired()
                        .HasColumnType("text");

                    b.Property<string>("IssueType")
                        .IsRequired()
                        .HasColumnType("text");

                    b.Property<Guid>("ReportId")
                        .HasColumnType("uuid");

                    b.HasKey("Id");

                    b.HasIndex("ReportId");

                    b.ToTable("REPORT_DETAILS", (string)null);
                });

            modelBuilder.Entity("AIArchitectureReviewer.Domain.Entities.RuleChunk", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uuid");

                    b.Property<string>("Content")
                        .IsRequired()
                        .HasColumnType("text");

                    b.Property<Vector>("Embedding")
                        .HasColumnType("vector(768)");

                    b.Property<Guid>("SystemRuleId")
                        .HasColumnType("uuid");

                    b.HasKey("Id");

                    b.HasIndex("Embedding");

                    NpgsqlIndexBuilderExtensions.HasMethod(b.HasIndex("Embedding"), "hnsw");
                    NpgsqlIndexBuilderExtensions.HasOperators(b.HasIndex("Embedding"), new[] { "vector_cosine_ops" });

                    b.HasIndex("SystemRuleId");

                    b.ToTable("RuleChunks");
                });

            modelBuilder.Entity("AIArchitectureReviewer.Domain.Entities.SystemRule", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uuid");

                    b.Property<string>("DiagramType")
                        .IsRequired()
                        .HasColumnType("text");

                    b.Property<bool>("IsActive")
                        .HasColumnType("boolean");

                    b.Property<string>("RegexOrCondition")
                        .IsRequired()
                        .HasColumnType("text");

                    b.Property<string>("RuleName")
                        .IsRequired()
                        .HasColumnType("text");

                    b.HasKey("Id");

                    b.ToTable("SYSTEM_RULES", (string)null);
                });

            modelBuilder.Entity("AIArchitectureReviewer.Domain.Entities.AnalysisReport", b =>
                {
                    b.HasOne("AIArchitectureReviewer.Domain.Entities.AiPrompt", "AiPrompt")
                        .WithMany("AnalysisReports")
                        .HasForeignKey("AiPromptId")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired();

                    b.Navigation("AiPrompt");
                });

            modelBuilder.Entity("AIArchitectureReviewer.Domain.Entities.ChatMessage", b =>
                {
                    b.HasOne("AIArchitectureReviewer.Domain.Entities.ChatSession", "ChatSession")
                        .WithMany("Messages")
                        .HasForeignKey("ChatSessionId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("ChatSession");
                });

            modelBuilder.Entity("AIArchitectureReviewer.Domain.Entities.Feedback", b =>
                {
                    b.HasOne("AIArchitectureReviewer.Domain.Entities.AnalysisReport", "Report")
                        .WithMany("Feedbacks")
                        .HasForeignKey("ReportId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Report");
                });

            modelBuilder.Entity("AIArchitectureReviewer.Domain.Entities.ReportDetail", b =>
                {
                    b.HasOne("AIArchitectureReviewer.Domain.Entities.AnalysisReport", "Report")
                        .WithMany("ReportDetails")
                        .HasForeignKey("ReportId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Report");
                });

            modelBuilder.Entity("AIArchitectureReviewer.Domain.Entities.RuleChunk", b =>
                {
                    b.HasOne("AIArchitectureReviewer.Domain.Entities.SystemRule", "SystemRule")
                        .WithMany("RuleChunks")
                        .HasForeignKey("SystemRuleId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("SystemRule");
                });

            modelBuilder.Entity("AIArchitectureReviewer.Domain.Entities.AiPrompt", b =>
                {
                    b.Navigation("AnalysisReports");
                });

            modelBuilder.Entity("AIArchitectureReviewer.Domain.Entities.AnalysisReport", b =>
                {
                    b.Navigation("Feedbacks");

                    b.Navigation("ReportDetails");
                });

            modelBuilder.Entity("AIArchitectureReviewer.Domain.Entities.ChatSession", b =>
                {
                    b.Navigation("Messages");
                });

            modelBuilder.Entity("AIArchitectureReviewer.Domain.Entities.SystemRule", b =>
                {
                    b.Navigation("RuleChunks");
                });
#pragma warning restore 612, 618
        }
    }
}
